### ISSUE TITLE
How to add text for enabled and disabled state?

### ISSUE THREAD

**Issue by TheHemantKaushik** [tiempham/react-native-base-switch#6]
![screen shot 2018-02-19 at 6 14 37 pm](https://user-images.githubusercontent.com/28451375/36378449-d965e752-15a0-11e8-89e6-5e57d45d38b9.png)
![screen shot 2018-02-19 at 6 15 02 pm](https://user-images.githubusercontent.com/28451375/36378452-d9a8ef5c-15a0-11e8-982b-3d16f3d3e3a1.png)

**Comment by tiempham** [comment]
Sorry. This option is not available!
